version: 2
jobs:
  build:
    working_directory: ./src
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.11

      - run:
          # Squashing image layers requires experimental mode
          name: Set docker experimental mode
          command: |
            ssh remote-docker \<<EOF
             sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
             sudo systemctl restart docker
            EOF
                  
      - run:
          name: Build application Docker image
          command: |
            docker build --squash -t app ./
