version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.11
      - run: |
          ssh remote-docker \<<EOF
            sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
            sudo systemctl restart docker
          EOF
                  
      - run:
          name: Build application Docker image
          command: |
            docker build --squash -t app ./
